/**
 * This file is generated by Phero.
 * https://github.com/phero-hq/phero
 * Do not edit this file by hand. Changes will be disregarded next time it's generated.
 **/

/* eslint-disable */
/* prettier-disable */

import { Fetch, BasePheroClient, Parser, ParseResult, parser } from "@phero/client";
const helloWorldService__helloWorld__parser: Parser<string> = parser.String;
function error_parser_helloWorldService(error: any): Error { if (error.name === "Error")
    return new Error(error.props.message);
else
    return new Error("Unknown Error"); }
export class PheroClient extends BasePheroClient {
    constructor(fetch: Fetch, url = "http://localhost:3030") { super(fetch, url); }
    helloWorldService = {
        helloWorld: async (name: string): Promise<string> => { return this.request<string>("helloWorldService", "helloWorld", { name }, error_parser_helloWorldService, helloWorldService__helloWorld__parser); }
    };
}
